plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.worksafepro.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.worksafepro.app'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main {
            java {
                exclude '**/PerfilActivity.java'
                exclude '**/AgendaActivity.java'
                exclude '**/RelatoriosActivity.java'
                exclude '**/TreinamentosActivity.java'
                exclude '**/EPIActivity.java'
                exclude '**/OcorrenciasActivity.java'
                exclude 'com/worksafepro/MainActivity.java'
                exclude '**/com/worksafepro/MainActivity.java'
                exclude '**/MainActivity.java'
            }
        }
    }
}
